name: eco_track
description: "A Flutter app for reporting cleanliness issues."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # Google Maps
  google_maps_flutter: ^2.5.0

  # Location & reverse geocoding
  geolocator: ^10.1.0
  geocoding: ^2.1.0

  # Google Places autocomplete (SAFE & MAINTAINED)
  google_places_flutter: ^2.0.6

  #firebase authentication
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4

  # iOS-style icons
  cupertino_icons: ^1.0.8

  

dev_dependencies:
  flutter_native_splash: ^2.4.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1


flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image.png
flutter_icons:
  android: true
  ios: true
  image_path: "assets/image.png"
  adaptive_icon_background: "#1E6F5C"
  adaptive_icon_foreground: "assets/image.png"
flutter_native_splash:
  color: "#1E6F5C"
  image: assets/image.png
  android: true
  ios: true
  fullscreen: true

